// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi59Smhz0nIYP1Qt7BTQGe1nFnK4Bngn0',
    appId: '1:664422940578:web:f126b5943fc46963567cfb',
    messagingSenderId: '664422940578',
    projectId: 'yo-yo-awesome-project',
    authDomain: 'yo-yo-awesome-project.firebaseapp.com',
    storageBucket: 'yo-yo-awesome-project.firebasestorage.app',
    measurementId: 'G-K3XZZCD53N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD_p3RtODvfV7Ku38LrP_8S-c_8srYw4k',
    appId: '1:664422940578:android:dedacd247c69c977567cfb',
    messagingSenderId: '664422940578',
    projectId: 'yo-yo-awesome-project',
    storageBucket: 'yo-yo-awesome-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVBOtDDOD6OcyhJ-nVz5QwUa0W7lykmTA',
    appId: '1:664422940578:ios:03665a2450254df6567cfb',
    messagingSenderId: '664422940578',
    projectId: 'yo-yo-awesome-project',
    storageBucket: 'yo-yo-awesome-project.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVBOtDDOD6OcyhJ-nVz5QwUa0W7lykmTA',
    appId: '1:664422940578:ios:03665a2450254df6567cfb',
    messagingSenderId: '664422940578',
    projectId: 'yo-yo-awesome-project',
    storageBucket: 'yo-yo-awesome-project.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi59Smhz0nIYP1Qt7BTQGe1nFnK4Bngn0',
    appId: '1:664422940578:web:56572be748453b40567cfb',
    messagingSenderId: '664422940578',
    projectId: 'yo-yo-awesome-project',
    authDomain: 'yo-yo-awesome-project.firebaseapp.com',
    storageBucket: 'yo-yo-awesome-project.firebasestorage.app',
    measurementId: 'G-B2ECCRYR6W',
  );
}
